# -*- coding: utf-8 -*-
"""2_Cluster_Small.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wx8v3GGgORaMFPcMx0X24gcvvpA1Xkep
"""

from sklearn.cluster import KMeans
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)

kmeans = KMeans(n_clusters=3)
kmeans.fit(data)

data['cluster'] = kmeans.labels_

plt.scatter(data['sepal length (cm)'], data['sepal width (cm)'], c=data['cluster'], cmap='viridis')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('K-Means Clustering')
plt.show()

"""Hierarchial Agglomerative Clustering"""

from sklearn.cluster import AgglomerativeClustering

agg = AgglomerativeClustering(n_clusters=3)

agg.fit(data)
data['cluster'] = agg.labels_
plt.scatter(data['sepal length (cm)'], data['sepal width (cm)'], c=data['cluster'], cmap='viridis')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('Agglomerative Clustering')
plt.show()

"""DBSCAN"""

from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=0.5, min_samples=5)

dbscan.fit(data)
data['cluster'] = dbscan.labels_
plt.scatter(data['sepal length (cm)'], data['sepal width (cm)'], c=data['cluster'], cmap='viridis')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('DBSCAN Clustering')
plt.show()





