# -*- coding: utf-8 -*-
"""matrix_multiplication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXufanfySKdxlzGfX6KHSaQ7-1cqdsJn
"""

def matrix_multiplication(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must equal number of rows in B")

    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            val = 0
            for k in range(len(B)):
                val += A[i][k] * B[k][j]
            row.append(val)
        result.append(row)

    return result

# Function to input a matrix from the user
def input_matrix(prompt):
    print(prompt)
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            row.append(float(input(f"Enter element at position ({i+1}, {j+1}): ")))
        matrix.append(row)
    return matrix

# Input matrices from the user
A = input_matrix("Enter matrix A:")
B = input_matrix("Enter matrix B:")

# Perform matrix multiplication
result = matrix_multiplication(A, B)

# Print the result
print("Result of matrix multiplication:")
for row in result:
    print(row)

